plugin: netbox.netbox.nb_inventory
api_endpoint: https://xglw4450.cloud.netboxapp.com
validate_certs: False
config_context: False
site_data: true
#query_filters:
#  - site: clab
device_query_filters:
  - has_primary_ip: 'true'
#  - tag: 'tag1'
  
